### ISSUE TITLE
Listagem de Eventos 

### ISSUE THREAD

**Issue by DH-97** [luke96neto/carcara#33]
EU desenvolvedor
QUERO criar uma lista de eventos
PARA exibir as informações de cada evento.

- [x] Definir lista de eventos
- [x] cadastra informação de cada eventos.

**Comment by DH-97** [comment]
![listagem de eventos](https://github.com/user-attachments/assets/0ddffed6-6115-4557-9669-0cdeddcf2bb8)

**Comment by Andersonjs99** [comment]
![image](https://github.com/user-attachments/assets/bdd7f5a9-ee09-472f-a989-bdf85d880cdb)
