### ISSUE TITLE
Cadastrar eventos

### ISSUE THREAD

**Issue by EMANUEBRIT** [luke96neto/carcara#5]
Eu como administrator do sistema 
Quero cadastrar os eventos em geral associando ao tipo de evento (externo, interno e etc.)
Para deixar mais fácil e rápido a entrega das informações à Comunidade do IFPE Igarassu

- [x] Criar o protótipo no Figma
- [ ] Criar o HTML
- [ ] Criar o CSS

**Comment by felipeknk** [comment]
![image](https://github.com/user-attachments/assets/a3aceb10-6a8a-4681-a289-57b5daf055cb)
